name: Rust CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.85.0
    - name: Install dependencies
      run: cargo install --path .
    - name: Build
      run: cargo build --verbose --all-features
    - name: Test
      run: cargo test --verbose --all-features
    - name: Clippy
      run: cargo clippy --verbose --all-features -- -D warnings
    - name: Format
      run: cargo fmt --verbose --all -- --check
    - name: Audit
      run: cargo audit --verbose